### PR TITLE
Fix LogBuilder.tileType

### LINKED ISSUE #2591: "to place a 2"
image

### PR DESCRIPTION
**Pull request by daniel-ziegler**
Fixes  #2591

### CODE REVIEW

**Review by sienmich — APPROVED** [review]

File: src/LogBuilder.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ export class LogBuilder {
     }
 
     public tileType(value: TileType): LogBuilder {
-      this.parameters.push(new LogMessageData(LogMessageDataType.TILE_TYPE, value.toString()));
+      this.parameters.push(new LogMessageData(LogMessageDataType.TILE_TYPE, TileType.toString(value)));
```
Comment (kberg) [inline src/LogBuilder.ts:90]: I appreciate that this alleviates the problem, but I would much prefer change be made on the client-side which has accesse to TileType.toString.

This change is not backward compatible, and doesn't fix any past games. The other path would have fixed all prior games.

Can you please switch to resolving this on the client side?

Comment (daniel-ziegler) [reply src/LogBuilder.ts:90]: Ah, I see how the system is meant to work. Will do.

Comment (kberg) [reply src/LogBuilder.ts:90]: :pray: thank you.
