### PR TITLE
Visual fixes 2

### LINKED ISSUE #866: Purple player displayed incorrectly on Turmoil board
turmoil_purple

### PR DESCRIPTION
**Pull request by alrusdi**
Visual bug fix #866
Language independent widget to choose player color on create-game form

### CODE REVIEW

File: src/components/CreateGameForm.ts [hunk 1]
```diff
@@ -292,6 +303,11 @@ export const CreateGameForm = Vue.component("create-game-form", {
                                 <i class="form-icon"></i> <span v-i18n>Random first player</span>
                             </label>
 
+                            <label class="form-switch" v-if="playersCount > 2">
+                                <input type="checkbox" v-model="randomSeat">
+                                <i class="form-icon"></i> <span v-i18n>Random seat</span>
```
Comment (nwai90) [inline src/components/CreateGameForm.ts:308]: Minor suggestion: Would "Shuffle player order" be more descriptive here?

Comment (alrusdi) [reply src/components/CreateGameForm.ts:308]: Shuffle player order - is great. I will change it.
Second suggestions sometimes not that good. Some of the my player groups wants manual seats distribution. I think it is ok to have 2 options here

**Comment by alrusdi** [comment]
@nwai90 we had a discussion about your suggestion to not make new option to shuffle players order. Everyone are ok with it.
So i've redone it just like you described. Thank you for participating!
