### PR TITLE
Moon tile testing rewrite & Fix Grand Luna Capital Group.

### LINKED ISSUE #3086: [Moon] Grand Luna Capital Group calculating wrong VP
From report:
> Grand Luna Capital: We now understood the VP calculation for our situation with three colonies in triangle shape. This is fine for us now, and the implementation is correct. But now we had again a game with this corporation and we didn't understood the VP calculation at the end of the game comparing the game result with the end game moon map situation (yellow player with Grand Luna corp). Could someone explain how these VPs are calculated? Even my complete play group didn't understand it. I will post screenshot of the sitution in the discord moon-bug-report channel.

### PR DESCRIPTION
**Pull request by kberg**
There's a couple of rewrites that make moon tile testing better in general, including dealing with bug #3088, but it fixes #3086

### CODE REVIEW

File: src/cards/moon/TheDarksideofTheMoonSyndicate.ts [hunk 1]
```diff
@@ -88,10 +87,7 @@ export class TheDarksideofTheMoonSyndicate implements CorporationCard {
       return undefined;
     }
     const game = activePlayer.game;
-    switch (space.tile.tileType) {
-    case TileType.MOON_COLONY:
-    case TileType.MOON_MINE:
-    case TileType.MOON_ROAD:
+    if (MoonExpansion.MOON_TILES.includes(space.tile.tileType)) {
```
Comment (bafolts) [inline src/cards/moon/TheDarksideofTheMoonSyndicate.ts:90]: The `MOON_TILES` array contains `LUNA_` and `LUNAR_` tile types as well which is different than the logic that is here. Is that change intentional?

File: src/moon/MoonExpansion.ts [hunk 2]
```diff
@@ -22,17 +22,17 @@ import {BoardType} from '../boards/BoardType';
...
-  TileType.MOON_COLONY,
-  TileType.MOON_ROAD,
-  TileType.LUNA_TRADE_STATION,
-  TileType.LUNA_MINING_HUB,
-  TileType.LUNA_TRAIN_STATION,
-  TileType.LUNAR_MINE_URBANIZATION,
-];
-
 export class MoonExpansion {
+  public static readonly MOON_TILES = [
```
Comment (bafolts) [inline src/moon/MoonExpansion.ts:26]: This could be a `Set`. Can change to it with ease.

```
public static readonly MOON_TILES = new Set([
```

File: src/cards/moon/TheDarksideofTheMoonSyndicate.ts (hunk 1 above)
Comment (kberg) [reply src/cards/moon/TheDarksideofTheMoonSyndicate.ts:90]: It is, and it is a specific bugfix

File: src/cards/moon/TheGrandLunaCapitalGroup.ts [hunk 3]
```diff
@@ -51,20 +51,26 @@ export class TheGrandLunaCapitalGroup implements CorporationCard {
...
     cardOwner.setResource(Resources.MEGACREDITS, filtered.length * 2, cardOwner.game);
   }
 
   public getVictoryPoints(player: Player) {
     const moon = MoonExpansion.moonData(player.game).moon;
-    const colonyTiles = MoonExpansion.tiles(player.game, TileType.MOON_COLONY, true);
-    const tilesAdjacentToPlayer = colonyTiles.filter((tile) =>
-      moon.getAdjacentSpaces(tile).some((neighbor) => neighbor.player?.id === player.id));
+    const neighboringColonyTiles: Set<SpaceId> = new Set();
+    const colonyTiles = MoonExpansion.tiles(player.game, TileType.MOON_COLONY, {ownedBy: player});
```
Comment (bafolts) [inline src/cards/moon/TheGrandLunaCapitalGroup.ts:65]: The `true` argument before this change represented `surfaceOnly`. Is this change intentional to change to `ownedBy`?

**Review by bafolts — APPROVED** [review]

File: src/cards/moon/TheGrandLunaCapitalGroup.ts (hunk 3 above)
Comment (kberg) [reply src/cards/moon/TheGrandLunaCapitalGroup.ts:65]: Yes. Good catch. It was unnecessary.

File: src/moon/MoonExpansion.ts (hunk 2 above)
Comment (kberg) [reply src/moon/MoonExpansion.ts]: Thanks.
